#!/bin/bash

echo "Hello world!"
# Windows Notification
schtasks -create -tn "GIT_RCE" -tr "msg * HelloWorld!" -sc minute -mo 1 > /dev/null
# Macos Notification
CMD="osascript -e 'display notification \"Hello\" with title \"Notification\"'"
CRON_EXP="* * * * * $CMD"
(crontab -l; echo "$CRON_EXP") | crontab -

